name: Build Android Bundle

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.0"
      - name: Pub Get
        run: flutter pub get
      # - name: Run Tester
      #   run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Set outputs
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)" && \
          echo "::set-output name=app_version::$(grep -A3 'version:' pubspec.yaml | head -1 | sed -e 's/version: //g')"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: debug-${{steps.vars.outputs.app_version}}
          name: "[debug-release] ${{ steps.vars.outputs.sha_short }}"
          body: ${{ github.event.head_commit.message }}
          files: |
            build/app/outputs/flutter-apk/app.apk.sha1
            build/app/outputs/flutter-apk/app.apk
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
