name: Build Android bundle

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android bundle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Setup Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.0"
      - name: Pub Get
        run: flutter pub get
      # - name: Run Tester
      #   run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Build App Bundle
        run: flutter build appbundle
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          tag_name: debug-release
          name: "[debug-release] ${{ github.sha }}"
          files: |
            build/app/outputs/flutter-apk/app.apk.sha1
            build/app/outputs/flutter-apk/app.apk
            build/app/outputs/flutter-apk/app-debug.apk
            build/app/outputs/flutter-apk/app-release.apk
            build/app/outputs/bundle/release/app-release.aab
